### ISSUE TITLE
s3 to ssh

### ISSUE THREAD

**Issue by ready4god2513** [seedifferently/boto_rsync#1]
How would I go about using ssh for the destination?

**Comment by seedifferently** [comment]
Please see the docs under the "usage" section:

> SOURCE and DESTINATION can either be a local path to a directory or specific file, a custom S3 URI to a directory or specific key in the format of s3://bucketname/path/or/key, or a S3 to S3 transfer using two S3 URIs.

At this time you can only transfer files locally <-> S3 and S3 <-> S3. Remote ssh transfer is something that will probably not be supported because in most cases you can just install it on the remote server and use it there.

**Comment by ready4god2513** [comment]
Unfortunately with Akamai that is not an option for me.
