### ISSUE TITLE
Error invalid literal for int() with base 10

### ISSUE THREAD

**Issue by ghost** [seedifferently/boto_rsync#2]
Traceback (most recent call last):
  File "/usr/local/bin/boto-rsync", line 1122, in <module>
    main()
  File "/usr/local/bin/boto-rsync", line 312, in main
    debug = int(a)
ValueError: invalid literal for int() with base 10: '/srv/htdocs/firstclass/dev/instalacoes/lojaskd/novalojaskd_R1900/prd/11000/11011'

if i use --access-key the error appear like:

ValueError: invalid literal for int() with base 10: '--access-key'

:C

**Comment by seedifferently** [comment]
Gabriel,

The -d/--debug option requires a parameter. From the docs: 

```
    -d/--debug <level>          Level 0 means no debug output (default), 1 means
                                normal debug output from boto, and 2 means boto
                                debug output plus request/response output from
                                httplib.
```

Are you specifying a debug level directly after the -d/--debug option? Please paste me the output of the command you are running.

Thanks,
Seth

**Comment by ghost** [comment]
sorry, i don't read the readme file, thnks!
