### ISSUE TITLE
All files get transferred every time.

### ISSUE THREAD

**Issue by drcongo** [seedifferently/boto_rsync#4]
Hey there.

Every time I run boto_rsync it transfers every single file from the source to the destination. The command I'm using to run it is:

`boto-rsync -v --access-key=XXXXXX --secret-key=XXXXXX --endpoint="s3-eu-west-1.amazonaws.com" /local/path/folder s3://bucketname/files/remote/path/folder`

I've got boto 2.4.1 installed though not sure if that's relevant.

Thanks.

**Comment by seedifferently** [comment]
Does it have the same effect if you add trailing slashes to your source and destination?

What OS are you on and what version of Python are you using?

**Comment by drcongo** [comment]
Hi again.

This was on OS X 10.7.3, Python 2.7.1. I've just tested again (without the trailing slashes) from inside an Ubuntu 12.04 VM and it worked perfectly, so I'll double check this on my MacBook Air again when I get home and see if the trailing slashes make a difference.

**Comment by drcongo** [comment]
btw, now that I have this working (in this https://bitbucket.org/drcongo/s3-backup ) I'd also like to say thanks! This is totally awesome.

**Comment by seedifferently** [comment]
Great, let me know what you find out. Glad this tool is helpful for you.

**Comment by drcongo** [comment]
I've been unable to reproduce this since I reported it so I can only assume it was down to something I had done wrong.
Thanks again.

**Comment by seedifferently** [comment]
Great, thanks.
